### DIFICULTY MODES ###
EASY = 1.1
MEDIUM = 1.25
HARD = 1.35
SUPER_HARD = 1.5
#######################

### CONFIGURATION ###
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800
SCREEN_COLOR = "black"
SCREEN_TITLE = "PONG GAME"
PADDLE1_COLOR = "white"
PADDLE2_COLOR = "red"
BALL_COLOR = "white"
STARTING_POS_LEFT = (-450, 0)
STARTING_POS_RIGHT = (450, 0)
LEFT_SCORE = (-100, 300)
RIGHT_SCORE = (100, 300)
DIFFICULTY = EASY
### CONFIGURATION END ###